@host=http://localhost:3001
@persons=/api/persons
@info=/info

GET {{host}}{{persons}}

###

GET {{host}}{{persons}}/684a763d2a96429d41b16ee5

###

DELETE {{host}}{{persons}}/684a1c6d7af54b1bfad37527

###

POST {{host}}{{persons}}
Content-Type: application/json

{
  "name": "Daniela Campo",
  "number": "040-3321234"
}

###

PUT {{host}}{{persons}}/684a763d2a96429d41b16ee5
Content-Type: application/json

{ "name": "Daniela Campo", "number": "040-6633234"}

###

GET {{host}}{{info}}
